name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - master   # Change if your default branch is not main

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Vite works well with Node 18

    # 3. Install dependencies
    - name: Install dependencies
      run: npm ci

    # 4. Build the project
    - name: Build Vite project
      run: npm run build

    - name: upload htaccess to dist
      run: cp .htaccess dist/

    # 5. Deploy via FTP
    - name: FTP Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        local-dir: dist/
        server-dir: public_html/
        dangerous-clean-slate: true

